config/routes.rb
Shop::Application.routes.draw do
  devise_for :users

  root :to => 'home_pages#welcome'
  resources :cart_items, :only => [:create, :destroy]
  resources :orders, :only => :create do
     get :preview, :on => :member
   end
  match 'current_cart' => 'carts#show', :as => :current_cart
  match "checkout" => "orders#checkout", :as => :checkout
  match "confirm" => "orders#confirm", :as => :confirm
  match "complete" => "orders#complete", :as => :complete
  
  namespace :admin do
    root :to => 'products#index'
    resources :products
    resources :orders, :only => [:index, :show, :destroy]
  end
  
  as :user do
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
    get "/register" => "devise/registrations#new"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :admin
end

app/views/users/login.html.erb
<h1><small>Login</small></h1>
<%= form_for :user, :url => user_session_path, :html => { :class => "custom nice" } do |f| %>
	<%= f.text_field :email, :placeholder => "Email", :class => "input-text" %>
  <%= f.password_field :password, :placeholder => "Password", :class => "input-text" %>
  <%= f.check_box :remember_me %>
  <%= f.label :remember_me, "Recuerda mis datos", :class => "inline" %>
	<div class="actions">
	  <%= f.submit 'Login', :class => "nice small radius blue button" %>
	</div>
	<%= link_to "¿Olvidaste tu contraseña?", new_password_path('user') %>
<% end %>

app/views/users/register.html.erb
<h1><small>Registrate</small></h1>
<%= form_for @user, :as => :user, :url => user_registration_path, :html => { :class => "custom nice" } do |f| %>
	<%= f.text_field :email, :placeholder => "Email", :class => "input-text" %>
	<%= f.password_field :password, :placeholder => "Contraseña", :class => "input-text" %>
	<%= f.password_field :password_confirmation, :placeholder => "Confirmar Contraseña", :class => "input-text" %>
	<div class="actions">
	  <%= f.submit 'Registrarte', :class => "nice small radius blue button" %>
	</div>
<% end %>