config/routes.rb
Shop::Application.routes.draw do
  devise_for :users

  root :to => 'home_pages#welcome'
  resources :cart_items, :only => [:create, :destroy]
  resources :orders, :only => :create do
     get :preview, :on => :member
   end
  match 'current_cart' => 'carts#show', :as => :current_cart
  match "checkout" => "orders#checkout", :as => :checkout
  match "confirm" => "orders#confirm", :as => :confirm
  match "complete" => "orders#complete", :as => :complete
  
  namespace :admin do
    root :to => 'products#index'
    resources :products
    resources :orders, :only => [:index, :show, :destroy]
  end
  
  as :user do
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
    get "/register" => "devise/registrations#new"
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items
  
  def empty?
    return true if items_in_cart.zero?
    return false
  end
  
  def items_in_cart
    cart_items.count
  end
  
  def total_price
    price = 0
    cart_items.each do |cart_item|
      price += cart_item.product.price
    end
    price
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CartsHelper
  def show
    @cart = current_cart
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def current_cart
    if session[:cart_id]
      begin
        @current_cart ||= Cart.find(session[:cart_id])
        session[:cart_id] = nil if @current_cart.purchased_at
      rescue Exception => e
        session[:cart_id] = nil 
      end
    end
    if session[:cart_id].nil?
      @current_cart = Cart.create!
      session[:cart_id] = @current_cart.id
    end
    @current_cart
  end
  
  def product_in_cart(product)
    current_cart.cart_items.each do |cart_item|
      return true if cart_item.product_id == product.id
    end
    false
  end
  
  def link_to_cart
    link_text = "Carro" + " de Compra " + "(#{current_cart.items_in_cart})"
    link_to( link_text, current_cart_url)
  end
end

app/views/carts/show.html.erb
<h2>Carro de compra</h2>

<% unless @cart.empty? %>
	<table id="shop_cart_table">
	  <thead>
	    <tr>
	      <th>Nº</th>
	      <th>Producto</th>
	      <th>Descripcion</th>
				<th>Cantidad</th>
	      <th>Precio</th>
	      <th>Eliminar</th>
	    </tr>
	  </thead>
	  <tbody>
	    <% @cart.cart_items.each_with_index do |cart_item, index| %>
	      <tr>
	        <td><%= index+1 %></td>
	        <td><%= cart_item.product.name %></td>
	        <td><%= cart_item.product.description %></td>
		      <td><%= cart_item.quantity %></td>
	        <td><%= cart_item.product.price %></td>
	        <td>
						<%= link_to "Eliminar", cart_item_path(:id => cart_item), :method => :delete, 
												:class => 'nice small radius red button' %>
					</td>
	      </tr>
	    <% end %>
	    <tr>
	      <td colspan="4"></td>
	      <td class="">TOTAL:</td>
	      <td><%= @cart.total_price %> &nbsp; €</td>
	    </tr>
	  </tbody>
	</table>
<% else %>
	Todavía no han sido añadidos productos al carro.
<% end %>

<div>
  <div>
    <%= link_to "SEGUIR COMPRANDO", root_path, :class => "nice small radius white button" %>
		<%= link_to "REALIZAR COMPRA", checkout_path, :class => "nice small radius white button" %>
    <%#= link_to "REALIZAR COMPRA", preview_order_path(@cart.id), :class => "nice small radius blue button" unless @cart.empty? %>
  </div>
</div>