config/routes.rb
Shop::Application.routes.draw do
  devise_for :users

  root :to => 'home_pages#welcome'
  resources :cart_items, :only => [:create, :destroy]
  resources :orders, :only => :create do
     get :preview, :on => :member
   end
  match 'current_cart' => 'carts#show', :as => :current_cart
  match "checkout" => "orders#checkout", :as => :checkout
  match "confirm" => "orders#confirm", :as => :confirm
  match "complete" => "orders#complete", :as => :complete
  
  namespace :admin do
    root :to => 'products#index'
    resources :products
    resources :orders, :only => [:index, :show, :destroy]
  end
  
  as :user do
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
    get "/register" => "devise/registrations#new"
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :description, :price
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(params[:product])
    if @product.save
      redirect_to [:admin, @product], :notice => "El producto se ha creado correctamente."
    else
      render :action => "new"
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to [:admin, @product], :notice => "El producto se ha actualizado correctamente."
    else
      render :action => "edit"
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def create_products_grid(products, &block)
    html = ""
    products.each_with_index do |product, index|
      html <<	"<div class=\"row\">" if (index % 3 == 0) || index == 0
    	  
    	content = capture(product, &block)
    	html << content_tag(:div, content, :class => 'four columns')
      
      html <<	"</div>" if (index+1) % 3 == 0 || (index+1 == products.size)
    end
	  html.html_safe
  end
end

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product], :html => { :class => "custom nice" } do |f| %>
    
	<%= f.label :name %>
  <%= f.text_field :name, :class => "input-text" %>
    
	<%= f.label :description %>
  <%= f.text_field :description, :class => "input-text" %>
    
	<%= f.label :price %>
  <%= f.text_field :price, :class => "input-text" %>

	<div class="actions">
	  <%= f.submit :class => "nice small radius blue button" %>
	  <%= link_to "Cancelar", admin_products_path, :class => "nice small radius white button" %>
	</div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editar productos</h1>

<%= render 'form' %>

app/views/admin/products/index.html.erb
<h2>Listado de Productos</h2>
<table>
	<thead>
	  <tr>
			<th>ID</th>
	    <th>Nombre</th>
	    <th>Descripcion</th>
	    <th>Precio</th>
	    <th></th>
	  </tr>
	</thead>
	<tbody>
		<% @products.each do |product| %>
		  <tr>
				<td><%= product.id %></td>
		    <td><%= product.name %></td>
		    <td><%= product.description %></td>
		    <td><%= product.price %></td>
		    <td>
					<%= link_to 'Ver', [:admin, product], :class => "nice small radius white button" %>
		    	<%= link_to 'Editar', edit_admin_product_path(product), :class => "nice small radius white button" %>
		    	<%= link_to 'Eliminar', [:admin, product], :confirm => 'Esta usted seguro?', :method => :delete, 
																										 :class => 'nice small radius red button' %>
				</td>
		  </tr>
		<% end %>
	</tbody>
</table>

<br />

<%= link_to 'Nuevo Producto', new_admin_product_path, :class => "nice small radius blue button" %>

app/views/admin/products/new.html.erb
<h1>Nuevo producto</h1>

<%= render 'form' %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @product.name %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @product.description %>
</p>

<p>
  <b>Precio:</b>
  <%= @product.price %>
</p>

<div class="actions">
	<%= link_to 'Editar', edit_product_path(@product), :class => "nice small radius white button" %>
	<%= link_to 'Listado', products_path, :class => "nice small radius white button" %>
</div>