config/routes.rb
Shop::Application.routes.draw do
  devise_for :users

  root :to => 'home_pages#welcome'
  resources :cart_items, :only => [:create, :destroy]
  resources :orders, :only => :create do
     get :preview, :on => :member
   end
  match 'current_cart' => 'carts#show', :as => :current_cart
  match "checkout" => "orders#checkout", :as => :checkout
  match "confirm" => "orders#confirm", :as => :confirm
  match "complete" => "orders#complete", :as => :complete
  
  namespace :admin do
    root :to => 'products#index'
    resources :products
    resources :orders, :only => [:index, :show, :destroy]
  end
  
  as :user do
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
    get "/register" => "devise/registrations#new"
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
	<div class="row">
		<div class="six columns">
	<h1><%= link_to "Administrative Zone", admin_root_path %></h1>
		</div>
		<div class="six columns navbar">
				<ul>
					<li><%= link_to "Tienda", root_path %></li>
					<li><%= link_to "Administrar productos", admin_products_path %></li>
					<li><%= link_to "Administrar pedidos", admin_orders_path %></li>
					<li><%= link_to("Logout", destroy_user_session_path, :method => :delete) %></li>
				</ul>
			</div>
	</div>
</header>

<div class="row">
	<%= messages_about_actions %>
	<%= yield %>
</div>

<footer>
	
</footer>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
	<div class="row">
		<div class="six columns">
			<h1><%= link_to "Example Shop", root_path %></h1>
		</div>
		<div class="six columns navbar">
				<ul>
					<% if user_signed_in? %>
						<li><%= "Hola, #{current_user.email}" %> </li>
					<% end %>
						<li><%= link_to "Tienda", root_path %></li>
						<li><%= link_to_cart %></li>
					<% if user_signed_in? %>
						<li><%= link_to "Administración", admin_root_path if current_user.admin? %> </li>
						<li><%= link_to "Logout", logout_path, :method => :delete %></li>
					<% else %>
						<li><%= link_to "Login", login_path %></li>
						<li><%= link_to "Registrarse", register_path %></li>
					<% end %>
				</ul>
			</div>
	</div>
</header>

<div class="row">
	<%= messages_about_actions %>
	<%= yield %>
</div>

<footer>
	
</footer>
</body>
</html>